spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://ber.cla2z9tnoqm3.ap-northeast-2.rds.amazonaws.com:3306/ber?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ber
    password: 12345678
  redis:
    host: localhost
    port: 6379

  security:
    jwt:
      header: Authorization
      secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK
      blacklist:
        access-token: BlackList_AccessToken_
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

    generate-ddl: true
    hibernate:
      ddl-auto: create

    properties:
      hibernate:
        format_sql: true
        show_sql: true

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

#    default_batch_fetch_size: 1000

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace
  # parameter Binding

---

spring:
  config:
    activate:
      on-profile: alpha
  jpa:
    hibernate:
      ddl-auto: validate
  datasource:
    url: jdbc:mysql://b2fe33867c5eb6:3bf314b4@us-cdbr-east-04.cleardb.com/heroku_74931efe97faf8e?reconnect=true
    username: root
    password: chldnjsdyd1@
  sql:
    init:
      mode: never